<?php echo $form = $this->service->getLoginForm(); ?>

<!--
<form action="index.html">

    <div class="notification information png_bg">
        <div>
            Just click "Sign In". No password needed.
        </div>
    </div>

    <p>
        <label>Username</label>
        <input class="text-input" type="text" />
    </p>
    <div class="clear"></div>
    <p>
        <label>Password</label>
        <input class="text-input" type="password" />
    </p>
    <div class="clear"></div>
    <p id="remember-password">
        <input type="checkbox" />Remember me
    </p>
    <div class="clear"></div>
    <p>
        <input class="button" type="submit" value="Sign In" />
    </p>

</form>-->