<?php echo $this->doctype ( Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL );?>
<?php $host = $this->domainLink (1);?>
<html>
<head>

	<?php echo $this->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html; charset=UTF-8' );?>
	<?php echo $this->headTitle ( $this->pageTitle());?>
	<?php

		$this->headScript()
            ->prependFile($host . "js/jquery-ui-1.8.11.custom.min.js")
			->prependFile($host . "js/jquery-1.5.2.min.js")
            ->appendFile($host . "js/tooltip.js")
			->appendFile($host . "js/simpla.jquery.configuration.js")
			->appendFile($host . "js/facebox.js")
			->appendFile($host . "js/jquery.form.js")
            ->appendFile($host . "js/jquery.transliterate-min.js")
            ->appendFile($host . "js/jquery.scrollfollow.js")
            ->appendFile($host . "js/basic.js")
            ->appendFile($host . "js/ajax.modal.submitter.js")
            ->appendFile($host . "js/jquery.cookie.js");

        $this->headLink()
            ->prependStylesheet($host . "css/reset.css")
			->appendStylesheet($host . "css/style.css")
			->appendStylesheet($host . "css/invalid.css")
            ->appendStylesheet($host . "css/form.css")
            ->appendStylesheet($host . "css/jquery.tooltip.css")
            ->prependStylesheet($host . "css/south-street/jquery-ui-1.8.11.custom.css");
	?>

	<!--[if lte IE 7]>
			<link rel="stylesheet" href="<?php echo $host ?>css/ie.css" type="text/css" media="screen" />
	<![endif]-->
    <!--[if IE 6]>
			<script type="text/javascript" src="<?php echo $host ?>js/DD_belatedPNG_0.0.7a.js"></script>
			<script type="text/javascript">
				DD_belatedPNG.fix('.png_bg, img, li');
			</script>
	<![endif]-->

	<?php echo $this->headLink ();?>
	<?php echo $this->headScript ();?>

</head>

	<body>
    <?php
 
        $fauxClass = 'faux';
        $sideBarBg = 'sidebar-background';
        $sideBarBgWrp = '';
        $sideBarBgWrpSmall = 'no-display';
        $mainCont = 'main-content';
        if ($this->hidden == 'true')
        {
            $mainCont = 'main-content-hidden';
            $fauxClass = 'faux-hidden';
            $sideBarBg = 'sidebar-background-hidden';
            $sideBarBgWrp = 'no-display';
            $sideBarBgWrpSmall = '';
        }
    ?>
    <div class="<?php echo $fauxClass; ?>">
        <div id="body-wrapper"> <!-- Wrapper for the radial gradient background -->



		<div id="sidebar" class="<?php echo $sideBarBg?>">

            <div id="sidebar-hidden" class="<?php echo $sideBarBgWrpSmall?>">
                <ul id="icons-menu" class="ui-widget ui-helper-clearfix show-button">
                    <?php
                        echo $this->iconButton(
                            null, 'ui-icon-circle-arrow-e', '', 'show-menu', '', ''
                        );
                    ?>
                </ul>

                <?php echo $this->smallMenu(); ?>
            </div>

           <div id="sidebar-wrapper" class="<?php echo $sideBarBgWrp?>"> <!-- Sidebar with logo and menu -->
           <ul id="icons-menu" class="ui-widget ui-helper-clearfix hide-button">
                <?php
                    echo $this->iconButton(
                        null, 'ui-icon-circle-arrow-w', '', 'hide', '', ''
                    );
               ?>
			</ul>

			<h1 id="sidebar-title"><a href="http://105.in.ua">Social Admin</a></h1>
		  
			<!-- Logo (221px wide) -->
			<a href="http://105.in.ua"><img id="logo" src="<?php echo $host ?>images/logo.png" alt="Simpla Admin logo" /></a>
		  
			<!-- Sidebar Profile links -->

            <?php
               echo $this->user();
               echo $this->menu();
           ?>
		</div></div> <!-- End #sidebar -->
		
		<div id="main-content" class="<?php  echo $mainCont ?>"> <!-- Main Content Section with everything -->
			
			<noscript> <!-- Show a notification if the user has disabled javascript -->
				<div class="notification error png_bg">
					<div>
						Javascript is disabled or is not supported by your browser. Please <a href="../../../browsehappy.com/index.htm" title="Upgrade to a better browser">upgrade</a> your browser or <a href="../../../www.google.com/support/bin/answer_2EEFB1D5.py" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
					</div>
				</div>
			</noscript>
			
			<!-- Page Head -->
		    <?php
                echo '<h2>' . $this->pageTitle() .'</h2>';
                echo '<div class="notifications"></div>';
                echo $this->layout()->content;
            ?>
			
			<div id="footer">
				<small> <!-- Remove this notice or replace it with whatever you want -->
						&#169; Copyright 2011 Fedor Petryk | Powered by
                    <a target=_blank href="http://themeforest.net/">Simpla Admin</a> |
                    <a href="#">Top</a>
				</small>
			</div><!-- End #footer -->
			
		</div> <!-- End #main-content -->
		
	</div></body>
  
</html>
