<div id="dashboard-buttons">
    <ul>
        <li>
            <a class="Book_phones tooltip" href="<? echo $this->domainLink(); ?>admin/menu/index"
                title = "Редактирование верхнего меню сайта">
                Меню сайта
            </a>
        </li>
        <li>
            <a class="Books tooltip" href="http://111.co.ua/admin/pages/index"
            title = "Редактирование статических страниц">
               Страници
            </a>

        </li>
        <li>
            <a class="Box_content tooltip" href="http://111.co.ua/admin/products/index"
            title = "Редактирование товаров сайта">
                Товары
            </a>
        </li>
        <li>
            <a class="Briefcase_files tooltip" href="http://111.co.ua/admin/news/index"
            title = "Редактирование новостей сайта. Новостная лента">
                 Новости
            </a>

        </li>
        <li>
            <a class="Clipboard_3 tooltip" href="http://111.co.ua/admin/categories/edit"
            title = "Редактирование категорий сайта">
                Категории
            </a>

        </li>
        <li>
            <a class="Globe tooltip" target="_blank" href="http://111.co.ua/"
                title = "Перейти на сайт в новом окне">
                На Сайт
            </a>
        </li>

    </ul>
    <div class="clear"></div>
</div>