<?php
//maximum file size in bytes. (Changable)
$MAX_SIZE = 1048576;
                            
//allowed filetypes. (Add as many as you like!)
$FILE_EXTS  = array('.jpeg','.jpg','.png','.gif'); 

//don't change this for security reasons.
$DELETABLE  = true;     
                          
$date = new Zend_Date();

$site_name = $_SERVER['HTTP_HOST'];
$url_dir = "http://".$_SERVER['HTTP_HOST'];
$url_this =  $this->linkTo()."/pages/images/";

$upload_dir = "../images/upload/";
$upload_dirf = "../images/upload/";
$upload_url = $url_dir."/upload/";
$message ="message";

if (!is_dir("./")) {
  if (!mkdir($upload_dir))
  	die ("Public files directory doesn't exist and creation failed.");
  if (!chmod($upload_dir,0755))
  	die ("change permission to 755 failed.");
}

if (array_key_exists('del', $_REQUEST))
if ($_REQUEST['del'] && $DELETABLE)  {
  $resource = fopen("../images/upload/log.txt","a");
  fwrite($resource,$date->toString("y-m-d h:i:s")."DELETE - ".$_SERVER['REMOTE_ADDR'].$_REQUEST['del']."\n");
  fclose($resource);
	if (file_exists($upload_dir.$_REQUEST['del'])){
    unlink($upload_dir.$_REQUEST['del']);
    print "<script>window.location.href='$url_this?message=".$_REQUEST['del']." deleted successfully!'</script>";
  }
}
if  (array_key_exists('userfile', $_FILES))
  if($_FILES['userfile']) {
  
   $resource = fopen("../images/upload/log.txt","a");
  fwrite($resource,$date->toString("y-m-d h:i:s")."UPLOAD - ".$_SERVER['REMOTE_ADDR']
            .$_FILES['userfile']['name']." "
            .$_FILES['userfile']['type']."\n");
  fclose($resource);

  $file_type = $_FILES['userfile']['type']; 
  $file_name = $_FILES['userfile']['name'];
  $file_ext = strtolower(substr($file_name,strrpos($file_name,".")));

  //File Size Check
  if ( $_FILES['userfile']['size'] > $MAX_SIZE) 
     $message = "The file size exceeds the limit of 1MB.";

  //File Extension Check
  else if (!in_array($file_ext, $FILE_EXTS))
     $message = "Sorry, $file_name($file_type) is not allowed to be uploaded.";
  else
     $message = do_upload($upload_dirf, $upload_url);

  print "<script>window.location.href='$url_this?message=$message'</script>";
}
else if  (array_key_exists('userfile', $_FILES))
{

		if (!$_FILES['userfile']);
}
else 
	$message = "Invalid File specified.";


$handle=opendir($upload_dir);
$filelist = "";
while ($file = readdir($handle)) {
   if(!is_dir($file) && !is_link($file)) {
    ##
	  $file_ext = strtolower(substr($file,strrpos($file,".")));
	  if (in_array($file_ext, $FILE_EXTS)){
	##
      $list_of_files[$file] = $date->toString("y-m-d h:i:s", filemtime($upload_dir.$file));
	  }
   }
}
##
if (!empty($list_of_files)){
## 
ksort($list_of_files);
if(isset($list_of_files)) {
foreach($list_of_files as $key => $value) {
$filelist .= "<div class='thumbnail'><a title='".$key."' onclick=\"insertPicture('".$key."', '/images/upload/".$key."');\"><img alt='".$key."' src='/images//upload/".$key."'></a><br /><a onclick='return pop()' href='$url_this?del=$key'>Delete</a></div>";

}
}
##
}
else {
$filelist = "<p style=\"color: #b80000; font-weight: bold;\">Нету загруженых изображений!</p>";
}
##
function do_upload($upload_dirf, $upload_url) {

	$temp_name = $_FILES['userfile']['tmp_name'];
	$file_name = $_FILES['userfile']['name']; 
    $file_name = str_replace("\\","",$file_name);
    $file_name = str_replace("'","",$file_name);
    $file_name = str_replace(" ","_",$file_name);
	$file_path = $upload_dirf.$file_name;

	//File Name Check
  if ( $file_name =="") { 
  	$message = "Invalid File Name Specified";
  	return $message;
  }

  $result  =  move_uploaded_file($temp_name, $file_path);
  if (!chmod($file_path,0755))
   	$message = "Change permission to 755 failed. Please manually chmod your public files folder to 755.";
  else
    $message = ($result)?"$file_name Файл загружен успешно!" :
     	      "An error occurred while uploading the file.";
  return $message;
}

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?php echo $this->LinkTo ();?>styles/img_upload.css"	media="all" rel="stylesheet" type="text/css" />

<title>Изображения</title>

<script type="text/javascript">
	function pop() {
	  var agree=confirm("Удалить?");
	  if (agree) {return true;} else {return false;}
	}
	function insertPicture(name, path)	{
		try {
			parent.$.markItUp( { replaceWith:'<img src="'+path+'" alt="[![Alt Text:!:'+name+']!]" />' } );
			parent.$('#imgs').dialog('destroy');
		} catch(e) {
			alert("No markItUp! Editor found");
		}
	}
</script>
</head>

<body>

<h4>Изображения</h4>

<p>Максимальный размер файла: 1MB (JPG, JPEG, PNG, GIF). <strong style="color: #b80000;"> <? if (array_key_exists('message',$_REQUEST)) echo $_REQUEST['message'];?></strong></p>

<form id="upload" enctype="multipart/form-data" method="post" action="/admin/pages/images/">
<p>Загрузить изображение: <input type="file" id="userfile" name="userfile" /></p>
<p><input type="submit" name="upload" value="Upload" class="button" onmouseover="this.className='buttonon'" 
		onmouseout="this.className='button'" onfocus="if (this.blur) this.blur();" /></p>
</form>

<p><strong>Загружены изображения:</strong></p>

<p> Нажмите на превью, что бы вставить на страницу!</p>

<p><?php echo $filelist?></p>

<br style="clear: both" />

</body>
</html>
