	<?php 
	    $form = $this->service->getAvatarForm();
	    $form->setAction($this->domainLink() . 'settings/loadavatar');
	    $settings_form = $this->service->getSettingsForm();
	    $settings_form->setAction($this->domainLink() . 'settings/editsettings');
	?>
	<div class="settings-form">
		<fieldset>
			<legend><?php echo $this->translation('edit_settings') ?></legend>
	           <div class="settings">
	   		   		<?php echo $settings_form; ?>
		       </div>
		</fieldset>
	</div>
