<?php
    $baseHost =  $this->domainLink (1);
    $host =  $this->domainLink ();
    $gridPrefix = $this->domainLink (3);

    $lang = Zend_Registry::get('language');
    $conf  = Zend_Registry::get('app_config');


    $this->headScript()
			->appendFile($gridPrefix . "jquery.simplegrid.js")
            ->appendFile($baseHost . "ckeditor/ckeditor.js")
            ->appendFile($baseHost . "ckeditor/config.js");

   $this->headLink()
            ->appendStylesheet($gridPrefix . "simplegrid.css")
?>

<script type='text/javascript'>
$(document).ready(function() {
     $(".simplegridy").simplegrid({
        url: '<?php echo $host ?>settings/index',
        save_url: "<?php echo $host ?>settings/inlinesave",
        edit_url: "<?php echo $host ?>settings/edit/id/",
        delete_url: "<?php echo $host ?>settings/delete/id/",
        colNames:['№',"<?php echo $this->translation('param_name') ?>",
                    "<?php echo $this->translation('param_value')?>",
                    "<?php echo $this->translation('param_description') ?>"],
        colModel :[    
            {name: 'id', width: "38px", index: true},
            {name: 'param_name', celledit: false, filter: 'name', width: "100px"},
            {name: 'param_value', celledit: true, filter: 'name', width: "100px"},
            {name: 'param_description', celledit: false, width: "200px"}
        ],
        fulledit: false,
        inlineedit: true,
        filters: true,
        sortdir: 'asc',
        sortcol: 'id',            
        rows: 10
     });
});

</script>

<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3></h3>
        <ul class="content-box-tabs">
            <li>
                <a href="#tab1" class="default-tab">
                    <?php echo $this->translation('system_settings_list')?>
                </a>
            </li> <!-- href must be unique and match the id of target div -->
            <li>
                <a href="#tab2" id="clicktab2">
                    <?php echo $this->translation('edit_system_settings')?>
                </a>
            </li>
        </ul>
    </div>
    <div class="content-box-content">
        <div class="error-wrapper">
            <?php echo $this->messenger($this->service->getError(), 0); ?>
        </div>

        <div class="message-wrapper">
            <?php echo $this->messenger($this->service->getMessage(), 1); ?>
        </div>

        
        <div class = 'grid-block tab-content default-tab' id="tab1">
            <div class = "simplegridy hastable"></div>
            <div class="clearfix"></div>
        </div>
        <div class = 'form tab-content' id="tab2">
            <?php
                $form = $this->service->getValidator();
                $form->setAction($host . 'settings/edit/');
                echo $form;
            ?>
        </div>
    </div>
</div>
 <div class="clear"></div>


<?php
	echo $this->modalDialog(
		$this->translation('confirm_delete_message'),
        'confirm',
        $this->translation('confirm_delete')
	);
?>
